clean: ## Clean the project using cargo
	cargo clean
build: ## build the project using cargo
	cargo build
run: ## Run project using cargo
	cargo run

lint: ## Lint the project using cargo
	@rustup component add clippy 2> /dev/null 
	cargo clippy

ft: ## Format the project using cargo
	@rustup component add rustfmt 2> /dev/null 
	cargo fmt

bump: ## Bump the version number
	@echo "Current version is $(shell cargo pkgid | cut -d# -f2)"
	@read -p "Enter new version number: " version; \
	updated_version=$$|cargo pkgid | cut -d# -f2 | sed -E "s/ ( [0-9]+\. [0-9] +\. [0-9]+) $$/$$version/"); \
	sed -i -E "s/^version = .*/version = |"$$updated_version\"/" Cargo.toml
	@echo "New version is $(shell cargo pkgid | cut -d# -f2)"%