SHELL := /bin/bash 
.PHONY: help

help:
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS=":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean the project using cargo
	cargo clean

build: ## build the project using cargo
	cargo build

run: ## Run project using cargo
	cargo run

lint: ## Lint the project using cargo
	@rustup component add clippy 2> /dev/null 
	cargo clippy

ft: ## Format the project using cargo
	@rustup component add rustfmt 2> /dev/null 
	cargo fmt

bump: ## Bump the version number in Cargo.toml
	@current=$$(cargo pkgid | cut -d# -f2); \
	echo "Current version is $$current"; \
	read -p "Enter new version number: " version; \
	sed -i.bak -E "s/^version = \".*\"/version = \"$$version\"/" Cargo.toml; \
	rm Cargo.toml.bak; \
	echo "New version is $$version"
